// vue/whi/src/components/detailPanel.vue
<template>
  <div class="detail-panel">
    <SelectionDetails v-if="isLoggedIn" />
    <Explanation v-else />
  </div>
</template>

<style>
.detail-panel {
  width: 300px;
  border-left: 2px solid #000000;
  font-family: Tahoma;
  text-align: center;
  padding-top: 12px;
}
</style>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import Explanation from "./details/explanation.vue";
import SelectionDetails from "./details/selectionDetails.vue";

@Options({
  components: {
    Explanation,
    SelectionDetails,
  },
  computed: {
    isLoggedIn() {
      return this.$store.state.isLoggedIn;
    },
  },
})
export default class DetailPanel extends Vue {}
</script>

// angular/whi/src/app/detailPanel.component.ts
import { Component } from '@angular/core';
import LoginStateService from './services/state/loginstate.service';
import Explanation from './details/explanation.component';
import SelectionDetails from './details/selectionDetails.component';

@Component({
  selector: 'DetailPanel',
  imports: [Explanation, SelectionDetails],
  template: `@if (isLoggedIn()) {
        <SelectionDetails />
      }
      @else {
        <Explanation />
      }
  `,
  styles: `
:host, .detail-panel {
  width: 300px;
  border-left: 2px solid #000000;
  font-family: Tahoma;
  text-align: center;
  padding-top: 12px;
}
  `
})
export default class DetailPanel {
  constructor(public loginStateService: LoginStateService) {}

  isLoggedIn() : boolean {
    return this.loginStateService.getIsLoggedIn() === true;
  }
}
