// vue/whi/src/components/details/selectionDetails.vue
<template>
  <div class="selection-details">
    <div class="cap-line">what is selected?</div>
    <br />
  </div>
</template>

<style>
.selection-details {
  display: flex;
  flex: 1;
  flex-flow: column nowrap;
}

.cap-line {
  font-size: 22px;
  font-weight: bold;
  text-align: center;
}
</style>

<script lang="ts">
import { Vue } from "vue-class-component";

export default class SelectionDetails extends Vue {}
</script>

// angular/whi/src/app/details/selectionDetails.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'SelectionDetails',
  imports: [],
  template: `<div class="selection-details">What is selected? Otherwise summarizing data</div>`,
  styles: `
    :host, .selection-details {
    display: flex;
    flex: 1;
    }`
})
export default class SelectionDetails {
}
