// react/whi/src/components/mapPanel.tsx
import { MapContainer, TileLayer } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';

export default function MapPanel () {

    return (
        <div className="mapPanel">
            <div id="map">
                This frontend development is currently discontinued. Please checkout the Angular or Vue Frontend.
            {/* <MapContainer center={[51.98, 5.91]} zoom={14} scrollWheelZoom={true}>
                <TileLayer
                minZoom={6}
                attribution='\u003ca href=\"https://www.maptiler.com/copyright/\" target=\"_blank\"\u003e\u0026copy; MapTiler\u003c/a\u003e \u003ca href=\"https://www.openstreetmap.org/copyright\" target=\"_blank\"\u003e\u0026copy; OpenStreetMap contributors\u003c/a\u003e'
                url="https://api.maptiler.com/maps/streets-v2/{z}/{x}/{y}.png?key=${key}"
                />
            </MapContainer> */}
            </div>
        </div>
    );
}

// svelte/whi/src/components/mapPanel.svelte
<script lang="ts">
  //import L from 'leaflet';
	
  // import L, { Map } from "leaflet";

  // import 'leaflet/dist/leaflet.css';

  //const initialView = [51.98, 5.91];

  // function createMap(container: any) {
  //   let m = L.map(container, {preferCanvas: true }).setView(initialView, 14 );
  //   L.tileLayer(
	//     'https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',
	//     {
	//       attribution: `&copy;<a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a>,
	//         &copy;<a href="https://carto.com/attributions" target="_blank">CARTO</a>`,
	//       subdomains: 'abcd',
  //       minZoom: 6,
	//     }
	//   ).addTo(m);

  //   return m;
  // }

  // function setupMap(container: any) {
  //   map = createMap(container);
  //   return {
  //     destroy: () => {
  //       map?.remove();
  //       map = null;
  //     }
  //   };
  // }

</script>

<style>
.map-panel {
  flex: 1;
  padding: 20px;
  font-size: 16px;
  font-family: Tahoma;
}

#map {
  width: 100%;
  height: 100%;
}
</style>

<div class="map-panel">
  <!-- <div id="map"></div> -->
  This frontend development is currently discontinued. Please checkout the Angular or Vue Frontend.
</div>
